// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"github.com/google/uuid"
)

type Ticket struct {
	ID           int32     `json:"id"`
	TicketUid    uuid.UUID `json:"ticketUid"`
	Username     string    `json:"username"`
	FlightNumber string    `json:"flightNumber"`
	Price        int32     `json:"price"`
	Status       string    `json:"status"`
}
