// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePrivilege(ctx context.Context, username string) (Privilege, error)
	CreatePrivilegeHistory(ctx context.Context, arg CreatePrivilegeHistoryParams) (PrivilegeHistory, error)
	DeletePrivilegeHistory(ctx context.Context, ticketUid uuid.UUID) error
	GetPrivilege(ctx context.Context, username string) (Privilege, error)
	GetPrivilegeById(ctx context.Context, id int32) (Privilege, error)
	GetPrivilegeHistory(ctx context.Context, ticketUid uuid.UUID) (PrivilegeHistory, error)
	ListPrivilegeHistories(ctx context.Context, privilegeID int32) ([]PrivilegeHistory, error)
	UpdatePrivilegeBalance(ctx context.Context, arg UpdatePrivilegeBalanceParams) error
}

var _ Querier = (*Queries)(nil)
