// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"time"
)

type Airport struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	City    string `json:"city"`
	Country string `json:"country"`
}

type Flight struct {
	ID            int32     `json:"id"`
	FlightNumber  string    `json:"flightNumber"`
	Datetime      time.Time `json:"datetime"`
	FromAirportID int32     `json:"fromAirportID"`
	ToAirportID   int32     `json:"toAirportID"`
	Price         int32     `json:"price"`
}
