// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	GetAirport(ctx context.Context, id int32) (Airport, error)
	GetFlight(ctx context.Context, flightNumber string) (Flight, error)
	ListAirports(ctx context.Context) ([]Airport, error)
	ListFlights(ctx context.Context) ([]Flight, error)
	ListFlightsWithOffsetLimit(ctx context.Context, arg ListFlightsWithOffsetLimitParams) ([]Flight, error)
}

var _ Querier = (*Queries)(nil)
